# config.yml

# Aquí puedes agregar configuraciones predeterminadas

# Configuración de pagos automáticos para policías
payments:
  interval: 1800 # Tiempo en segundos (30 minutos)

  police:
    amount: 10

multas:
  comision_policia: 0.5

loteria:
  loteria_base_precio: 0

banco:
  Cuenta_lvl_1: 0
  Cuenta_lvl_2: 0
  Cuenta_lvl_3: 0