main: com.Evan_Roams.Os_Druks_Rp_P
version: 1.0.0
name: Orion_Druks_Roleplay_Plugin
author: Evan_Roams
api-version: 1.12
depend: [Vault, Essentials]

permissions:

  os_druks_rp_p.admin:
    description: Permiso para usar el el multar
    default: false
  os_druks_rp_p.commands.tablet:
    description: Permiso para usar el comando /roleplay tablet
    default: false

  os_druks_rp_p.policia.multar:
    description: Permiso para usar el el multar
    default: false

  os_druks_rp_p.policia.servicio:
    description: Permiso para estar en servicio de policía
    default: false

  os_druks_rp_p.commands.policia.servicio:
    description: Permiso para estar en servicio de policía
    default: false

  os_druks_rp_p.policia.radio:
    description: Permiso para estar en la radio de policia
    default: false



commands:
  roleplay:
    description: Comando Principal
    aliases:
      - mp

  rpadmin:
    description: Comando para radio depolicía
    aliases:
      - 911

  rptienda:
    description: Comando para tienda
    aliases:
      - rptienda

  tablet:
    description: Comando para abrir tablet
    aliases:
      - tableta
  dni:
    description: Comando para obtener dni
    aliases:
      - cedula
  policia:
    description: Comando para policía
    aliases:
      - 911
  radio:
    description: Comando para radio depolicía
    aliases:
      - 911


